# Generated by Django 5.1.6 on 2025-02-19 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('private', models.BooleanField(default=False)),
                ('admins', models.ManyToManyField(related_name='admin_communities', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='communities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
