# Generated by Django 5.1.6 on 2025-02-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_post_trustworthiness_alter_post_author_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='members_count',
            field=models.IntegerField(default=0),
        ),
    ]
