# Generated by Django 5.1.6 on 2025-02-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moyn_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moynuser',
            name='profile_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
